[2025-09-08T17:01:51.972+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-08T17:01:51.979+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-09-04T00:00:00+00:00 [queued]>
[2025-09-08T17:01:51.984+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-09-04T00:00:00+00:00 [queued]>
[2025-09-08T17:01:51.984+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-09-08T17:01:51.996+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): taskBranch> on 2025-09-04 00:00:00+00:00
[2025-09-08T17:01:51.999+0000] {standard_task_runner.py:72} INFO - Started process 16348 to run task
[2025-09-08T17:01:52.002+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'cron_catchup_backfill', 'taskBranch', 'scheduled__2025-09-04T00:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmpxjittjly']
[2025-09-08T17:01:52.003+0000] {standard_task_runner.py:105} INFO - Job 118: Subtask taskBranch
[2025-09-08T17:01:52.041+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-09-04T00:00:00+00:00 [running]> on host codespaces-9bd7b3
[2025-09-08T17:01:52.117+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='loonycorn' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskBranch' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-04T00:00:00+00:00'
[2025-09-08T17:01:52.118+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-08T17:01:52.134+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-09-08T17:01:52.140+0000] {python.py:240} INFO - Done. Returned value was: taskC
[2025-09-08T17:01:52.141+0000] {branch.py:38} INFO - Branch into taskC
[2025-09-08T17:01:52.141+0000] {skipmixin.py:230} INFO - Following branch {'taskC'}
[2025-09-08T17:01:52.147+0000] {skipmixin.py:278} INFO - Skipping tasks [('taskE', -1)]
[2025-09-08T17:01:52.176+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-08T17:01:52.176+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskBranch, run_id=scheduled__2025-09-04T00:00:00+00:00, execution_date=20250904T000000, start_date=20250908T170151, end_date=20250908T170152
[2025-09-08T17:01:52.216+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-08T17:01:52.255+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-08T17:01:52.277+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
