[2025-09-08T17:04:01.516+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-08T17:04:01.524+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-08-09T12:00:00+00:00 [queued]>
[2025-09-08T17:04:01.529+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-08-09T12:00:00+00:00 [queued]>
[2025-09-08T17:04:01.529+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-09-08T17:04:01.542+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): taskBranch> on 2025-08-09 12:00:00+00:00
[2025-09-08T17:04:01.545+0000] {standard_task_runner.py:72} INFO - Started process 17381 to run task
[2025-09-08T17:04:01.548+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'cron_catchup_backfill', 'taskBranch', 'scheduled__2025-08-09T12:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmpaxfibao4']
[2025-09-08T17:04:01.549+0000] {standard_task_runner.py:105} INFO - Job 118: Subtask taskBranch
[2025-09-08T17:04:01.579+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskBranch scheduled__2025-08-09T12:00:00+00:00 [running]> on host codespaces-9bd7b3
[2025-09-08T17:04:01.623+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='loonycorn' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskBranch' AIRFLOW_CTX_EXECUTION_DATE='2025-08-09T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-09T12:00:00+00:00'
[2025-09-08T17:04:01.624+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-08T17:04:01.634+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-09-08T17:04:01.639+0000] {python.py:240} INFO - Done. Returned value was: taskD
[2025-09-08T17:04:01.639+0000] {branch.py:38} INFO - Branch into taskD
[2025-09-08T17:04:01.640+0000] {skipmixin.py:230} INFO - Following branch {'taskD'}
[2025-09-08T17:04:01.645+0000] {skipmixin.py:278} INFO - Skipping tasks [('taskE', -1), ('taskC', -1)]
[2025-09-08T17:04:01.663+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-08T17:04:01.664+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskBranch, run_id=scheduled__2025-08-09T12:00:00+00:00, execution_date=20250809T120000, start_date=20250908T170401, end_date=20250908T170401
[2025-09-08T17:04:01.680+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-09-08T17:04:01.694+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-08T17:04:01.701+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
